[[main]]
  name = "Nosotros"
  pageRef = "quienes-somos"
  weight = 10

[[main]]
  name = "Crónicas"
  pageRef = "blog"
  weight = 20

[[main]]
  name = "Proyectos"
  pageRef = "proyectos"
  weight = 30

[[main]]
  name = "YouTube"
  pageRef = "youtube"
  weight = 40

[[main]]
  name = "Agenda"
  pageRef = "agenda"
  weight = 50

[[main]]
  name = "Transparencia"
  pageRef = "transparencia"
  weight = 60

[[main]]
  name = "Conversemos"
  pageRef = "contacto"
  weight = 70

[[footer]]
  name = "Conversemos"
  pageRef = "contacto"
  weight = 10

[[footer]]
  name = "Transparencia"
  pageRef = "transparencia"
  weight = 20